name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Set to your desired Node.js version

    #Handling front
    #- name: Install dependencies for front
     # run: npm install
     # working-directory: ./public_html/frontend

#    - name: Build Next.js app
 #     run: npm run build
  #    working-directory: ./public_html/frontend

    # Uncomment the below lines when you have frontend tests set up
    #- name: Run tests for front
    #  run: npm test
    #  working-directory: ./public_html/frontend

    # Handling api
#    - name: Install dependencies for api
#      run: npm install
#      working-directory: ./domains/api.ugolok.shop/public_html/API

#    - name: Run tests for api
#      run: npm test
#      working-directory: ./domains/api.ugolok.shop/public_html/API

    - name: Deploy to server
      if: success()
      env:
        PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
        HOST: ${{ secrets.DEPLOY_HOST }}
        USER: ${{ secrets.DEPLOY_USER }}
      run: ./deploy.sh
